### ISSUE TITLE
Baseline 5 Minute Resting Pulse: No error messages were displayed after closing laptop and then removing ear sensor

### ISSUE THREAD

**Issue by choipaul92** [EmotionCognitionLab/lipbelly#10] opened 2023-09-01 17:15 UTC
During my baseline [4], I took off my earsensor for 1 minute and the app DID NOT inform of any issues. Instead it continued until I placed the ear sensor back on my earlobe.

Here's more info for context: 
8/30/23, 3:49PM 

[1] BASELINE: I tried logging into the app, but it got stuck on "logging in." So, I checked the console and saw 2 errors (which were not recorded). I proceeded to quit and relaunch the app, which resolved the issue.

[2] BASELINE: After 1 minute of baseline, I closed the laptop for 30 seconds. Upon reopening the laptop, the baseline resumed.

[3] BASELINE: After 2 minutes, I unplugged the ear sensor for 30 seconds. The baseline continued for 10 seconds, until I received the message “no or poor signal detected.” After 10 seconds, the screen displayed “the session has ended because it has been a long time since the device…” I plugged it back in, and the app returned to the start of the 5-minute baseline.

[4] BASELINE: **After 2 minutes of baseline, I removed the ear sensor from my ear for 1 minute. The baseline timer continued without any warning or “no or poor signal detected” message.** For the next minute of baseline, I changed my breathing to deep inhaling through the nose and exhaling through the mouth. For the last minute of baseline, I resumed normal breathing.

**Comment by noah10** [comment] 2023-09-07 16:33
I was unable to reproduce this. I took the sensor off my ear and 20 seconds later got the "no or poor signal detected" error. Are you able to reproduce it?

**Comment by choipaul92** [comment] 2023-10-02 21:07
ctrl+shift+L was pressed upon logging in 

Just tested this. After 1 minute of baseline breathing, I took off the ear sensor & I got the message ("no or poor signal detected") 18 seconds later. 

At 2:48 minutes remaining, I closed my laptop and after opening it, it resumed. At 1:30 minutes remaining, I took off my ear sensor for 1 minute (I did not receive "no or poor signal detected this time). At :30 seconds remaining mark, I placed my ear sensor back on my earlobe and finished the baseline.

**Comment by noah10** [comment] 2023-10-02 21:12
Can you please try these steps and see if they reproduce the problem?

1. Begin breathing session.
2. After 1 minute, close your laptop lid for 30 seconds then re-open it.
3. Assuming that the timer resumes, wait 30 seconds and then remove the sensor from your ear. Do not replace it on your ear.

**Comment by choipaul92** [comment] 2023-10-02 21:13
Second baseline session (paced breathing): 

At 4 minutes remaining mark, I took off my ear sensor and it did stop while giving me a "no or poor signal detected". However, before I could put my ear sensor back on my earlobe, the session resumed  for 1 minute or so (cannot confirm the exact time because there is no timer on the paced breathing). I  placed the ear sensor back onto my earlobe at 2 minute remaining mark. After a ~45 seconds, the app froze on me. I pressed "start" and it continued with "1 minute remaining"

**Comment by choipaul92** [comment] 2023-10-09 23:30
Follow up on Noah's request:

After 1 minute of starting the session, I closed the laptop for 30 seconds. After opening the laptop, the timer stopped and I received the message “the session has ended because it has been a long time.” (observed this two times). 

On the third try, the timer did not stop & I did not receive an error message. When I took off the ear sensor from my earlobe, I did get an error message 15 seconds after. I completed the remaining baseline session.

**Comment by noah10** [comment] 2023-10-09 23:38
OK - it sounds like the only real problem here is that the app behavior is inconsistent when you close the laptop lid. Unfortunately that's not something we have any control over - it's really all about the OS (and, secondarily, emWave) at that point. I'm going to go ahead and close this issue.

**Closed by noah10** 2023-10-09 23:38 UTC
